modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "vs_takeoff"
version = "${version}"
displayName = "VS Takeoff"
authors = "Me, Myself, and I."
description = '''
A propulsion addon for the VS2 Physics Engine. Based off Eureka.
'''
#logoFile = ""

[[dependencies.vs_takeoff]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_takeoff]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_takeoff]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[${vs2_version},)"
ordering = "AFTER"
side = "BOTH"

#[[dependencies.vs_takeoff]]
#modId = "create"
#mandatory = true
#versionRange = "[0.5.0e,)"
#ordering = "NONE"
#side = "BOTH"
